basePath: /api
definitions:
  books.BookListResponse:
    description: Response containing a list of books
    properties:
      data:
        items:
          $ref: '#/definitions/queries.BookResponse'
        type: array
    type: object
  queries.BookResponse:
    properties:
      author_id:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  ratings.RatingRequest:
    properties:
      book_id:
        type: string
      heart_score:
        type: number
      poo_score:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API that will change the world
  title: BS Books API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get a list of all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/books.BookListResponse'
            type: array
      summary: Get list of books
      tags:
      - books
  /ratings:
    post:
      consumes:
      - application/json
      description: Create a new rating for a book
      parameters:
      - description: Rating to create
        in: body
        name: rating
        required: true
        schema:
          $ref: '#/definitions/ratings.RatingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create a new rating
      tags:
      - ratings
swagger: "2.0"
